swagger: '2.0'
info:
  version: 1.0.0
  title: Via-Movie
  description: This is a simple microservice that helps find movie's trailer
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http

paths:
  /trailer/movie/{id}:
    get:
      tags:
        - Trailer
      parameters:
        - name: id
          in: path
          required: true
          description: The movie name to retrieve the trailer
          type: string
      responses:
        200:
          description: Return the movie trailer info
        404:
          description: movie/trailer NOT FOUND